### ISSUE TITLE
Colaborar en el proyecto Devtech	

### ISSUE THREAD

**Issue by chachoariel** [JoaquinFranich/devtech-podcast-web#1]
# Colaborar en el equipo DevTech 
Hola Joaquin quiero colaborar en el proyecto como miembro del equipo podcast DevTech
Agrego mi tarjeta en la posicion 2
![image](https://user-images.githubusercontent.com/43642915/178974890-a811151e-54dd-4957-9b8a-de8ddc3544e2.png)

Saludos 👍

**Comment by JoaquinFranich** [comment]
Muy bueno, Ariel.
Excelente aporte.

Saludos!
